### ISSUE TITLE
regression in multipolygon building

### ISSUE THREAD

**Issue by tyrasd** [GIScience/oshdb#334]
### Bug Description
likely a regression in #249 

### How to Reproduce
```bash
curl -X GET "http://localhost:8082/elementsFullHistory/geometry?bpolys=%7B%20%20%20%22type%22%3A%20%22FeatureCollection%22%2C%20%20%20%22features%22%3A%20%5B%20%20%20%20%20%7B%20%20%20%20%20%20%20%22type%22%3A%20%22Feature%22%2C%20%20%20%20%20%20%20%22properties%22%3A%20%7B%7D%2C%20%20%20%20%20%20%20%22geometry%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22Polygon%22%2C%20%20%20%20%20%20%20%20%20%22coordinates%22%3A%20%5B%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2011.54837%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2048.16312%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2011.5507%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2048.16312%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2011.5507%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2048.1647%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2011.54837%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2048.1647%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2011.54837%2C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2048.16312%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%20%20%20%20%20%20%20%20%20%20%20%5D%20%20%20%20%20%20%20%20%20%5D%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%20%20%20%5D%20%7D&clipGeometry=true&filter=landuse%3D*&properties=tags&time=2008-01-01%2C2021-01-01" -H  "accept: application/json"
```

```
Caused by: java.util.NoSuchElementException: null
	at java.base/java.util.LinkedList.getFirst(LinkedList.java:248) ~[na:na]
	at org.heigit.bigspatialdata.oshdb.util.geometry.OSHDBGeometryBuilder.cutAtSegment(OSHDBGeometryBuilder.java:411) ~[oshdb-util-0.6.1.jar:na]
	at org.heigit.bigspatialdata.oshdb.util.geometry.OSHDBGeometryBuilder.mergeTouchingRings(OSHDBGeometryBuilder.java:354) ~[oshdb-util-0.6.1.jar:na]
	at org.heigit.bigspatialdata.oshdb.util.geometry.OSHDBGeometryBuilder.getMultiPolygonGeometry(OSHDBGeometryBuilder.java:244) ~[oshdb-util-0.6.1.jar:na]
	at hdb.util.celliterator.CellIterator.constructClippedGeometry(CellIterator.java:428) ~[oshdb-util-0.6.1.jar:na]
	at org.heigit.bigspatialdata.oshdb.util.celliterator.CellIterator.lambda$iterateByContribution$7(CellIterator.java:691) ~[oshdb-util-0.6.1.jar:na]
```

### Expected behaviour
no exception

### System information
Please complete the following information:
 - OSHDB Version: 0.6.1

**Comment by tyrasd** [comment]
this is potentially related to the following exception @joker234 found in our logs:

```
Jan 18 15:31:56 heigitsv01 ignite.sh[1582]: [15:31:56,858][SEVERE][pub-#42439%ohsome%][GridJobWorker] Failed to execute job due to unexpected runtime exception [jobId=57ae6b70771-ce3021f3-cf4c-42eb-a81b-32b54710ccd4, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=org.heigit.bigspatialdata.oshdb.api.mapreducer.backend.OSHDBIgniteMapReduceComputeTask, dep=SharedDeployment [rmv=false, super=GridDeployment [ts=1610913488529, depMode=SHARED, clsLdr=GridDeploymentClassLoader [id=beac8e11771-13957c01-6ac6-4e1f-b5c0-78d60d880b4b, singleNode=false, nodeLdrMap=HashMap {ce3021f3-cf4c-42eb-a81b-32b54710ccd4=06d66a70771-ce3021f3-cf4c-42eb-a81b-32b54710ccd4}, p2pTimeout=60000, usrVer=0, depMode=SHARED, quiet=false], clsLdrId=beac8e11771-13957c01-6ac6-4e1f-b5c0-78d60d880b4b, userVer=0, loc=false, sampleClsName=org.heigit.bigspatialdata.oshdb.api.mapreducer.backend.MapReducerIgniteAffinityCall$GetMatchingKeysPreflightLocalPeek, pendingUndeploy=false, undeployed=false, usage=1]], taskClsName=org.heigit.bigspatialdata.oshdb.api.mapreducer.backend.OSHDBIgniteMapReduceComputeTask, sesId=27ae6b70771-ce3021f3-cf4c-42eb-a81b-32b54710ccd4, startTime=1610983882139, endTime=9223372036854775807, taskNodeId=ce3021f3-cf4c-42eb-a81b-32b54710ccd4, clsLdr=GridDeploymentClassLoader [id=beac8e11771-13957c01-6ac6-4e1f-b5c0-78d60d880b4b, singleNode=false, nodeLdrMap=HashMap {ce3021f3-cf4c-42eb-a81b-32b54710ccd4=06d66a70771-ce3021f3-cf4c-42eb-a81b-32b54710ccd4}, p2pTimeout=60000, usrVer=0, depMode=SHARED, quiet=false], closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, internal=false, topPred=o.a.i.i.cluster.ClusterGroupAdapter$AttributeFilter@a3f8b2c, subjId=ce3021f3-cf4c-42eb-a81b-32b54710ccd4, mapFut=IgniteFuture [orig=GridFutureAdapter [ignoreInterrupts=false, state=INIT, res=null, hash=211080481]], execName=null], jobId=57ae6b70771-ce3021f3-cf4c-42eb-a81b-32b54710ccd4], err=no outgoing dirEdge found [ (11.549398014153159, 48.163554176141545, NaN) ]]                                                              
Jan 18 15:31:56 heigitsv01 ignite.sh[1582]: org.locationtech.jts.geom.TopologyException: no outgoing dirEdge found [ (11.549398014153159, 48.163554176141545, NaN) ]
…
Jan 18 15:31:56 heigitsv01 ignite.sh[1582]:         at org.heigit.bigspatialdata.oshdb.util.geometry.fip.FastPolygonOperations.intersection(FastPolygonOperations.java:179)                                                                                                                          
…
```
